### ISSUE TITLE
Persona login not working on install webapp

### ISSUE THREAD

**Issue by ppapadeas** [mozilla/marketpulse#110]
When using marketpulse as an installed webapp (tested on Android) Persona login is not working. Clicking on the button to login, does nothing. Probably something to do with target on <a>

**Comment by Chaasof** [comment]
Also in the website : I have always this message : "Login failed. Please make sure that you are an accepted Mozillian. "

**Comment by comzeradd** [comment]
@Chaasof Are you trying with the email you have on mozillians.org?

**Comment by Chaasof** [comment]
of course @comzeradd

**Comment by comzeradd** [comment]
Just tested on Firefox OS 2.0 and it seems to work fine.
