### ISSUE TITLE
Cherry Mobile in list

### ISSUE THREAD

**Issue by bobreyes** [mozilla/marketpulse#114]
Should be Cherry Mobile, Ace NOT Chery, Mobile Ace.

Thanks!

**Comment by comzeradd** [comment]
@ppapadeas Can you confirm this?

**Comment by ppapadeas** [comment]
Indeed. Please change maker to Cherry Mobile (from Chery) and device to Ace (from Mobile Ace)

**Comment by johngian** [comment]
Fixed in prod.
