### ISSUE TITLE
Map in a popup box

### ISSUE THREAD

**Issue by ashickurnoor** [mozilla/marketpulse#115]
I tried to input some device info. When I tried to locate my position in the map, it is hard to do so. It will be better if we can have a popup box for better location pointing as like[1].

[1] https://reps.mozilla.org/events/new/

**Comment by comzeradd** [comment]
Did you try this on mobile or desktop? Regarding mobile, the map is taking almost the full width of the page, so a pop up will not make any significant change.

We try to avoid breaking up the UI unless is really necessary.

**Comment by comzeradd** [comment]
One more thing to add on the above, the app is mostly intended to be used on mobile, that's why we try hard to avoid modals and pop-ups.
