### ISSUE TITLE
Mock up UI for price submission

### ISSUE THREAD

**Issue by ppapadeas** [mozilla/marketpulse#12]

**Comment by ppapadeas** [comment]
https://partinfra.etherpad.mozilla.org/market-pulse-specs

**Comment by comzeradd** [comment]
So what works here:
- Location: We use html5 geoleocation and adjust the map on the right spot. Regardless if the automatic geolocation works or not the user can navigate through the map and manually pick shop's location. No geocoding currently implemented. UX-wise the user doesn't need to know Geocoding details (they probably already know where they are), so we do geocoding at the backend.
- Form fields: Tied on what we have from the specs and the work that has been done on #18 
- Plan prices: Ability to add more plans. This should need some tweaking after we finalize and merge the models.

**Comment by comzeradd** [comment]
![shot](https://cloud.githubusercontent.com/assets/939357/6188424/8b9d3c80-b399-11e4-92e1-b2a04df568de.jpg)

**Comment by comzeradd** [comment]
![shot](https://cloud.githubusercontent.com/assets/939357/6192044/00fdbd20-b3b7-11e4-94f4-149e7aea4ef0.jpg)

**Comment by ppapadeas** [comment]
A couple of comments here:
- Add another plan -> Add another price (and made a button 'blue')
- "Is this *" headers should be slightly smaller
- Comment section should be spaced more.
- Submit button probably green?
