### ISSUE TITLE
Tabzilla is not showing in actual size

### ISSUE THREAD

**Issue by hossainalikram** [mozilla/marketpulse#120]
In marketpulse's website, If i click on Tabzilla, The contents are not in actual size, like what we see in other Mozilla sites when we click on Tabzilla. Apparently the content seems small comparing to the other sites . I have also attached a image of what i think is wrong. Thanks!
![a](https://cloud.githubusercontent.com/assets/8605491/6817384/f2aa85d2-d2c9-11e4-8478-3f9ef889c408.JPG)

**Comment by comzeradd** [comment]
Thanks for reporting this. It seems that the problem is caused by bootstrap's css. The only way to fix this without messing with bootstrap upstream code is to overwrite some tabzilla css values.

I just opened a PR about this.
