### ISSUE TITLE
Ability to add freetext (non fxos) competitive devices

### ISSUE THREAD

**Issue by comzeradd** [mozilla/marketpulse#126]

**Comment by ppapadeas** [comment]
- Change wording on add new to "New Device Price"
- On "Device" section add a toggle for FirefoxOS Device (default =1)
- When FireroxOS Device then dropdown as is
- When not FirefoxOS Device hide device dropdown, show freeform text (with placeholder Device Model)

**Comment by akatsoulas** [comment]
Closed via #148
