### ISSUE TITLE
Clone of issues - missing data

### ISSUE THREAD

**Issue by emmairwin** [mozilla/marketpulse#170]
I created a new record
https://marketpulse.mozilla.community/fxosprice/contribution/149/

Then I cloned it

https://marketpulse.mozilla.community/fxosprice/contribution/150/

I could see the prices before I saved the clone, but when I load it up again, there are no prices, and no fields to add them either.   https://marketpulse.mozilla.community/fxosprice/contribution/150/edit/

**Comment by johngian** [comment]
Closing this one after #179
