### ISSUE TITLE
Upvoting & Verified  (are these the same?)

### ISSUE THREAD

**Issue by emmairwin** [mozilla/marketpulse#171]
There's some confusion about what upvoting does.
And how verification works, can you please provide some steps to test?  Thanks

**Comment by emmairwin** [comment]
Testing for me 

1) Select a recording of another user, upvote it.  'X' in verified column changes to a check mark.   

I'll leave this open though, because I'm wondering if it will eventually sort these entries higher according to the number of upvotes?

**Comment by akatsoulas** [comment]
@emmairwin contributions are not sorted by votes right now. I am going to open a new PR addressing this issue. Nice catch :)

**Comment by akatsoulas** [comment]
Regarding the question on the title of the issue, you are correct, upvoting and verified are the same. Do you feel this naming convention causes confusion?

**Comment by emmairwin** [comment]
@akatsoulas yes, I think upvoting means something different.   Can we change the name to verify?  We can still sort by that, but it removes that confusion.  Thanks!
