### ISSUE TITLE
Photos are not associated with price recording

### ISSUE THREAD

**Issue by emmairwin** [mozilla/marketpulse#173]
Can we please have a way to associate photos with a price collection record? For now I will tell contributors to add a link to the contribution associated.  thanks!

**Comment by emmairwin** [comment]
I want to add that by making photos themselves contributions, it detracts from the value of good contributions.  A data-entry requirement must be a reference to a data recording.  We can enforce this manually for now, but will need revisited.  Thanks again

**Comment by comzeradd** [comment]
The specs were defined around making photo upload a totally new activity. For cases that are not tied to shop prices (billboards, promotions, screenshots, etc.). So we probably need to redefine the place we want photos to have inside marketpulse as an activity.

**Comment by emmairwin** [comment]
ok...  Photos were intended to be part of a single report, but we can get around it for now. In training I say they have to add the link in comments.     When we redefined it would be better to have an  automated way to link.  thanks
