### ISSUE TITLE
Delete test entries

### ISSUE THREAD

**Issue by emmairwin** [mozilla/marketpulse#185]
https://marketpulse.mozilla.community/activities/  

Is it possible to delete all my test entries?

**Comment by johngian** [comment]
Hey Emma should I delete all your contributions since 13 May or is there any valid one?

**Comment by emmairwin** [comment]
delete all please!

On Fri, May 15, 2015 at 5:35 AM, John Giannelos notifications@github.com
wrote:

> Hey Emma should I delete all your contributions since 13 May or is there
> any valid one?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/marketpulse/issues/185#issuecomment-102386905
> .

## 

Emma Irwin
@sunnydeveloper
Mozilla Reps Council Member

**Comment by emmairwin** [comment]
Thanks!
