### ISSUE TITLE
Incorrect URLs in education mozilla guide

### ISSUE THREAD

**Issue by DineshMv** [mozilla/marketpulse#188]
I tried to visit the websites provided here ( http://education.mozilla-community.org/modules/marketpulse_activities/step_2/) Missplaced url at 
[" >Printable Checklist

> Web App fields(and how to use them)
> Pricing & Plan Scenarios "]
> Also one URL missing in wiki mozilla.
> Here i attach a few images of incorrect URLs
> ![capture-20150517-060408](https://cloud.githubusercontent.com/assets/10209762/7668665/7b5d42e0-fc62-11e4-8bd2-f460e8cfbbfe.jpg)
> ![capture-20150517-062406](https://cloud.githubusercontent.com/assets/10209762/7668666/7b62d4ee-fc62-11e4-86c8-c4661377d7dd.jpg)
> ![capture-20150517-065340](https://cloud.githubusercontent.com/assets/10209762/7668667/7b685d42-fc62-11e4-8e81-c6f2ed9d26a3.jpg)

**Comment by comzeradd** [comment]
So it seems that the educational guide has changed url. @emmairwin Can you confirm and point the new one?

**Comment by emmairwin** [comment]
@comzeradd thanks for flagging this - now fixed.

**Comment by comzeradd** [comment]
I pushed a [fix](https://github.com/comzeradd/marketpulse/commit/1f351a51c1f9bb3e8b5ce0b822b6957bf386d583) for the url at marketpulse the home page. I think there is still a dead link on the introduction page of the educational guide. The link that points to step 1 seems to be wrong.

**Comment by emmairwin** [comment]
Thanks @comzeradd the link is:  http://education.mozilla-community.org/modules/marketpulse/participation_ladder   

Can you tell me where I can change this on the App itself?  Natalia is reporting it as broken, but I'm not sure where that is.
