### ISSUE TITLE
Firefox Device name not mentioned 

### ISSUE THREAD

**Issue by AkshayTiwari** [mozilla/marketpulse#190]
The Firefox OS device "spice fire one MI-FX2"  is not available in the dropdown list in the marketpulse fxos device price page.

**Comment by AkshayTiwari** [comment]
and the device exists, just in case :P 
http://www.saholic.com/mobile-phones/spice-fire-one-mi-fx2-1012486

**Comment by emmairwin** [comment]
Thanks for reporting this!   Please @ppapadeas is it possible to have this as a p1 fix?

**Comment by emmairwin** [comment]
@comzeradd

**Comment by ppapadeas** [comment]
@comzeradd please proceed with Maker: Spice & Model: Fire One Mi-FX2

**Comment by johngian** [comment]
Fixed in prod.

**Comment by emmairwin** [comment]
thanks!
