### ISSUE TITLE
Adding New Device -  500 Error

### ISSUE THREAD

**Issue by emmairwin** [mozilla/marketpulse#192]
![26996ebb714c2fa6bf688bb7195ef54e524a8e8148ac](https://cloud.githubusercontent.com/assets/60618/8150930/0d1c3b04-12b2-11e5-910a-ded0ec777402.png)

Reported by a contributor

**Comment by emmairwin** [comment]
<img src="//csa-discourse-uploads.s3.amazonaws.com/2700795e285f872024bc2e4a58c36155b8088f7dddb6.png" width="690" height="373">

**Comment by emmairwin** [comment]
yeah It is still happening, I have try to add an image , and i get this message ==> "

```
  Please correct the following errors
```

<img src="//csa-discourse-uploads.s3.amazonaws.com/2700795e285f872024bc2e4a58c36155b8088f7dddb6.png" width="690" height="373">

**Comment by emmairwin** [comment]
On my side - I just can't add an image, I just get the error message over and over , even when all fields are correct.

**Comment by johngian** [comment]
@emmairwin
Verified it locally. I will try to open a PR today and do a release tomorrow.

**Comment by johngian** [comment]
Closing this one after #195
