### ISSUE TITLE
Foxfood: Marketpulse app - Persona login not working

### ISSUE THREAD

**Issue by emmairwin** [mozilla/marketpulse#200]
https://bugzilla.mozilla.org/show_bug.cgi?id=1177429

**Comment by ppapadeas** [comment]
Is this still an issue?

**Comment by comzeradd** [comment]
From what we have witnessed there is a problem with some old version of FxOS. But this is Persona's known issue and not specific to Marketpulse. So I suggest we close it and re-open if we find a Marketpulse specific login issue.
