### ISSUE TITLE
Enable data export from /admin

### ISSUE THREAD

**Issue by johngian** [mozilla/marketpulse#21]

**Comment by akatsoulas** [comment]
In case this is helpful:
https://github.com/thoas/django-data-exporter

**Comment by johngian** [comment]
`django-data-exporter` requires celery to work. I suggest we don't add the overhead to deploy celery at this point and use `django-import-export`.

**Comment by akatsoulas** [comment]
Didn't know that! Just added a note here in case it was helpful.
