### ISSUE TITLE
Logo and feel for MarketPulse

### ISSUE THREAD

**Issue by ppapadeas** [mozilla/marketpulse#8]

**Comment by elioqoshi** [comment]
@ppapadeas  What format does the logo need to be? And also what will the background color be?
So I know how to adjust the logo

**Comment by comzeradd** [comment]
My default answer to this is always transparent svg :)

**Comment by ppapadeas** [comment]
Hey Elio!

Do you have the sources for the logo? Can you push them here? Thanks!
